/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.search;

import com.toedter.calendar.DateUtil;
import common.CrudEnum;
import controller.StudentController;
import controller.sub.StudentWindowController;
import entities.Student;
import java.time.LocalDate;
import java.time.Month;
import javax.swing.JLabel;
import javax.swing.JTable;
import model.StudentTableModel;
import utils.DateUtils;

/**
 *
 * @author NHI
 */
public class FrStudentInfo extends javax.swing.JFrame {

    /**
     * Creates new form FrStudentAdd
     */
    private final JLabel lbStudentEventInfo;

    public FrStudentInfo(JLabel lbStudentEventInfo, StudentTableModel model, JTable tbStudent, CrudEnum crudEnum, Student studentInfo,int selectedRow) {
        this.lbStudentEventInfo = lbStudentEventInfo;
        this.model = model;
        this.tbStudent = tbStudent;
        this.crudEnum = crudEnum;
        this.selectedRow = selectedRow;
        initComponents();
        this.setTitle(getSTitle());
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        
        // start page
        final StudentWindowController studentWindowController = new StudentWindowController(btSubmit, tfStudentId, tfStudentName, lbdateOfBirth, tfPhoneNumber, buttonGroup, tfFlink, taAddress, taDescrition, tfWorkPlace, lbMessage, this, lbStudentEventInfo, model, tbStudent);
        studentWindowController.setEvent(tbStudent,crudEnum,selectedRow);
        lbdateOfBirth.setDate(DateUtils.convertLdatatoUDate(LocalDate.of(1998, Month.MARCH, 20)));
        lbMessage.setVisible(false);
        if (crudEnum == CrudEnum.EDIT) {
            studentWindowController.setStudentInfo(studentInfo);
        }
    }

    public String getSTitle() {
        return crudEnum == crudEnum.ADD ? "Thêm mới học viên" : "Cập nhập thông tin học viên";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        pnMain = new javax.swing.JPanel();
        lbStudentId = new javax.swing.JLabel();
        tfStudentId = new javax.swing.JTextField();
        lbStudentName = new javax.swing.JLabel();
        tfStudentName = new javax.swing.JTextField();
        lbBirth = new javax.swing.JLabel();
        tfPhoneNumber = new javax.swing.JTextField();
        lbPhoneNumber = new javax.swing.JLabel();
        lbWorkPlace = new javax.swing.JLabel();
        tfWorkPlace = new javax.swing.JTextField();
        lbDescrible = new javax.swing.JLabel();
        lbAddress = new javax.swing.JLabel();
        tfFlink = new javax.swing.JTextField();
        lbFlink = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        taDescrition = new javax.swing.JTextArea();
        scrollPane2 = new javax.swing.JScrollPane();
        taAddress = new javax.swing.JTextArea();
        lbGender = new javax.swing.JLabel();
        rbtMale = new javax.swing.JRadioButton();
        rbtFemale = new javax.swing.JRadioButton();
        lbdateOfBirth = new com.toedter.calendar.JDateChooser();
        pnTop = new javax.swing.JPanel();
        lbMessage = new javax.swing.JLabel();
        btSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMain.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Thông tin học viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14)))); // NOI18N

        lbStudentId.setText("Mã học viên:");

        tfStudentId.setEditable(false);
        tfStudentId.setText("13");
        tfStudentId.setEnabled(false);
        tfStudentId.setMinimumSize(new java.awt.Dimension(6, 26));
        tfStudentId.setPreferredSize(new java.awt.Dimension(6, 26));
        tfStudentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentIdActionPerformed(evt);
            }
        });

        lbStudentName.setText("Họ tên(*):");

        tfStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStudentNameActionPerformed(evt);
            }
        });

        lbBirth.setText("Ngày sinh(*):");

        tfPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPhoneNumberActionPerformed(evt);
            }
        });

        lbPhoneNumber.setText("Số điện thoại(*):");

        lbWorkPlace.setText("Nơi làm việc:");

        tfWorkPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfWorkPlaceActionPerformed(evt);
            }
        });

        lbDescrible.setText("Mô tả:");

        lbAddress.setText("Địa chỉ:");

        tfFlink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFlinkActionPerformed(evt);
            }
        });

        lbFlink.setText("Tài khoản(*):");

        taDescrition.setColumns(20);
        taDescrition.setRows(5);
        scrollPane.setViewportView(taDescrition);

        taAddress.setColumns(20);
        taAddress.setRows(5);
        scrollPane2.setViewportView(taAddress);

        lbGender.setText("Giới tính:");

        buttonGroup.add(rbtMale);
        rbtMale.setText("Nam");
        rbtMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtMaleActionPerformed(evt);
            }
        });

        rbtFemale.setText("Nữ");
        rbtFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtFemaleActionPerformed(evt);
            }
        });

        lbdateOfBirth.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbStudentId)
                            .addComponent(lbStudentName)
                            .addComponent(lbBirth)
                            .addComponent(lbPhoneNumber)
                            .addComponent(lbGender))
                        .addGap(6, 6, 6)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbFlink)
                            .addComponent(lbAddress)
                            .addComponent(lbDescrible)
                            .addComponent(lbWorkPlace))
                        .addGap(20, 20, 20)
                        .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(tfFlink)
                            .addComponent(scrollPane)
                            .addComponent(tfWorkPlace)))
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(rbtMale)
                        .addGap(18, 18, 18)
                        .addComponent(rbtFemale)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnMainLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbdateOfBirth, tfPhoneNumber, tfStudentId, tfStudentName});

        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbStudentId)
                    .addComponent(tfStudentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFlink))
                .addGap(25, 25, 25)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbStudentName)
                    .addComponent(tfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbAddress)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbBirth)
                    .addComponent(lbDescrible)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbPhoneNumber)
                    .addComponent(tfPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWorkPlace)
                    .addComponent(tfWorkPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbGender)
                    .addComponent(rbtMale)
                    .addComponent(rbtFemale))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnMainLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lbdateOfBirth, tfFlink, tfPhoneNumber, tfStudentId, tfStudentName, tfWorkPlace});

        getContentPane().add(pnMain, java.awt.BorderLayout.CENTER);

        pnTop.setFocusable(false);

        lbMessage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMessage.setForeground(new java.awt.Color(255, 0, 0));
        lbMessage.setText("Vui lòng nhập đầy đủ thông tin bắt buộc");

        btSubmit.setBackground(new java.awt.Color(0, 153, 0));
        btSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btSubmit.setText("Lưu dữ liệu");
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnTopLayout = new javax.swing.GroupLayout(pnTop);
        pnTop.setLayout(pnTopLayout);
        pnTopLayout.setHorizontalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(btSubmit)
                .addGap(30, 30, 30))
        );
        pnTopLayout.setVerticalGroup(
            pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTopLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(pnTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSubmit)
                    .addComponent(lbMessage)))
        );

        getContentPane().add(pnTop, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSubmitActionPerformed

    private void tfStudentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentIdActionPerformed

    private void tfStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStudentNameActionPerformed

    private void tfPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPhoneNumberActionPerformed

    private void tfWorkPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfWorkPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWorkPlaceActionPerformed

    private void tfFlinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFlinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFlinkActionPerformed

    private void rbtMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtMaleActionPerformed

    private void rbtFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrStudentInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new FrStudentInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSubmit;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbBirth;
    private javax.swing.JLabel lbDescrible;
    private javax.swing.JLabel lbFlink;
    private javax.swing.JLabel lbGender;
    private javax.swing.JLabel lbMessage;
    private javax.swing.JLabel lbPhoneNumber;
    private javax.swing.JLabel lbStudentId;
    private javax.swing.JLabel lbStudentName;
    private javax.swing.JLabel lbWorkPlace;
    private com.toedter.calendar.JDateChooser lbdateOfBirth;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnTop;
    private javax.swing.JRadioButton rbtFemale;
    private javax.swing.JRadioButton rbtMale;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTextArea taAddress;
    private javax.swing.JTextArea taDescrition;
    private javax.swing.JTextField tfFlink;
    private javax.swing.JTextField tfPhoneNumber;
    private javax.swing.JTextField tfStudentId;
    private javax.swing.JTextField tfStudentName;
    private javax.swing.JTextField tfWorkPlace;
    // End of variables declaration//GEN-END:variables
    private StudentTableModel model;
    private JTable tbStudent;
    private CrudEnum crudEnum;
    private int selectedRow;
}
