/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import common.MenuEnum;
import controller.Navigator;
import dto.MenuDto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author NHI
 */
public class FrMain extends javax.swing.JFrame {

    public void list() {

        super.list(); //To change body of generated methods, choose Tools | Templates.
    }

    public FrMain() {
        initComponents();
        this.setTitle("Student Tracking");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        lbLogo.setIcon(new ImageIcon(getClass().getResource(utils.ImageUtils.LOGO_BKIT_PATH)));
        Navigator navigator = new Navigator(pnMainView);
        navigator.setStartPage();
        final List<MenuDto> menus = new ArrayList<>();
        menus.add(new MenuDto(MenuEnum.HOMEPAGE, pnHomePage, lbHomePage));
        menus.add(new MenuDto(MenuEnum.STUDENT_MANAGER, pnStudentMan, lbStudentMan));
        menus.add(new MenuDto(MenuEnum.COURSE_MANAGER, pnCourseMan, lbCourseMan));
        menus.add(new MenuDto(MenuEnum.CLASS_MANAGER, pnClassMan, lbClassMan));
        menus.add(new MenuDto(MenuEnum.STATICTIS, pnStatistical, lbStatistical));

        navigator.setEvent(menus);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLeft = new javax.swing.JPanel();
        pnApp = new javax.swing.JPanel();
        lbApp = new javax.swing.JLabel();
        pnMenu = new javax.swing.JPanel();
        pnHomePage = new javax.swing.JPanel();
        lbHomePage = new javax.swing.JLabel();
        pnStudentMan = new javax.swing.JPanel();
        lbStudentMan = new javax.swing.JLabel();
        pnCourseMan = new javax.swing.JPanel();
        lbCourseMan = new javax.swing.JLabel();
        pnClassMan = new javax.swing.JPanel();
        lbClassMan = new javax.swing.JLabel();
        pnStatistical = new javax.swing.JPanel();
        lbStatistical = new javax.swing.JLabel();
        pnLogo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        pnMainView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnLeft.setBackground(new java.awt.Color(0, 0, 0));

        pnApp.setBackground(new java.awt.Color(255, 0, 102));
        pnApp.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 15));

        lbApp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbApp.setForeground(new java.awt.Color(255, 255, 255));
        lbApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ung_dung_white_24dp.png"))); // NOI18N
        lbApp.setText("Quản lý học viên ");
        lbApp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnApp.add(lbApp);

        pnMenu.setBackground(new java.awt.Color(0, 0, 0));
        pnMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 12, 1, 12));
        pnMenu.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

        pnHomePage.setBackground(new java.awt.Color(96, 100, 191));

        lbHomePage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbHomePage.setForeground(new java.awt.Color(255, 255, 255));
        lbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu0_white_24dp.png"))); // NOI18N
        lbHomePage.setText("Màn hình chính");
        lbHomePage.setFocusTraversalPolicyProvider(true);
        pnHomePage.add(lbHomePage);

        pnMenu.add(pnHomePage);

        pnStudentMan.setBackground(new java.awt.Color(76, 175, 80));

        lbStudentMan.setBackground(new java.awt.Color(76, 175, 80));
        lbStudentMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStudentMan.setForeground(new java.awt.Color(255, 255, 255));
        lbStudentMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu1_white_24dp.png"))); // NOI18N
        lbStudentMan.setText("Quản lý học viên");
        pnStudentMan.add(lbStudentMan);

        pnMenu.add(pnStudentMan);

        pnCourseMan.setBackground(new java.awt.Color(76, 175, 80));

        lbCourseMan.setBackground(new java.awt.Color(76, 175, 80));
        lbCourseMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbCourseMan.setForeground(new java.awt.Color(255, 255, 255));
        lbCourseMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu2_white_24dp.png"))); // NOI18N
        lbCourseMan.setText("Quản lý khóa học");
        pnCourseMan.add(lbCourseMan);

        pnMenu.add(pnCourseMan);

        pnClassMan.setBackground(new java.awt.Color(76, 175, 80));

        lbClassMan.setBackground(new java.awt.Color(76, 175, 80));
        lbClassMan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbClassMan.setForeground(new java.awt.Color(255, 255, 255));
        lbClassMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu3_white_24dp.png"))); // NOI18N
        lbClassMan.setText("Quản lý lớp học ");
        pnClassMan.add(lbClassMan);

        pnMenu.add(pnClassMan);

        pnStatistical.setBackground(new java.awt.Color(76, 175, 80));

        lbStatistical.setBackground(new java.awt.Color(76, 175, 80));
        lbStatistical.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbStatistical.setForeground(new java.awt.Color(255, 255, 255));
        lbStatistical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_menu4_white_24dp.png"))); // NOI18N
        lbStatistical.setText("Thống kê dữ liệu");
        pnStatistical.add(lbStatistical);

        pnMenu.add(pnStatistical);

        pnLogo.setBackground(new java.awt.Color(0, 0, 0));
        pnLogo.add(lbLogo);

        javax.swing.GroupLayout pnLeftLayout = new javax.swing.GroupLayout(pnLeft);
        pnLeft.setLayout(pnLeftLayout);
        pnLeftLayout.setHorizontalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnApp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnLeftLayout.setVerticalGroup(
            pnLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLeftLayout.createSequentialGroup()
                .addComponent(pnApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );

        getContentPane().add(pnLeft, java.awt.BorderLayout.LINE_START);

        pnMainView.setLayout(new java.awt.BorderLayout(30, 30));
        getContentPane().add(pnMainView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbApp;
    private javax.swing.JLabel lbClassMan;
    private javax.swing.JLabel lbCourseMan;
    private javax.swing.JLabel lbHomePage;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbStatistical;
    private javax.swing.JLabel lbStudentMan;
    private javax.swing.JPanel pnApp;
    private javax.swing.JPanel pnClassMan;
    private javax.swing.JPanel pnCourseMan;
    private javax.swing.JPanel pnHomePage;
    private javax.swing.JPanel pnLeft;
    private javax.swing.JPanel pnLogo;
    private javax.swing.JPanel pnMainView;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnStatistical;
    private javax.swing.JPanel pnStudentMan;
    // End of variables declaration//GEN-END:variables
}
