/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author NHI
 */
public class pnHomePage extends javax.swing.JPanel {

    /**
     * Creates new form pnHomePage
     */
    public pnHomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCourse = new javax.swing.JPanel();
        lbCourseIcon = new javax.swing.JLabel();
        lbCourseInfo = new javax.swing.JLabel();
        lbCourseQty = new javax.swing.JLabel();
        pnStudent = new javax.swing.JPanel();
        lbStudentIcon = new javax.swing.JLabel();
        lbStudenInfo = new javax.swing.JLabel();
        lbStudentQty = new javax.swing.JLabel();
        pnMessageHint = new javax.swing.JPanel();
        lbMessageIcon = new javax.swing.JLabel();
        lbMessageInfo = new javax.swing.JLabel();
        lbMessageQty = new javax.swing.JLabel();

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 30, 30));

        pnCourse.setBackground(new java.awt.Color(255, 0, 0));

        lbCourseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_trangchu1_white_24dp.png"))); // NOI18N

        lbCourseInfo.setBackground(new java.awt.Color(255, 255, 255));
        lbCourseInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbCourseInfo.setText("Khóa học");

        lbCourseQty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbCourseQty.setText("100");

        javax.swing.GroupLayout pnCourseLayout = new javax.swing.GroupLayout(pnCourse);
        pnCourse.setLayout(pnCourseLayout);
        pnCourseLayout.setHorizontalGroup(
            pnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCourseLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbCourseIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbCourseQty)
                    .addComponent(lbCourseInfo))
                .addGap(40, 40, 40))
        );
        pnCourseLayout.setVerticalGroup(
            pnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCourseLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbCourseQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbCourseInfo)
                    .addComponent(lbCourseIcon))
                .addGap(29, 29, 29))
        );

        add(pnCourse);

        pnStudent.setBackground(new java.awt.Color(0, 0, 255));

        lbStudentIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_trangchu2_white_24dp.png"))); // NOI18N

        lbStudenInfo.setBackground(new java.awt.Color(255, 255, 255));
        lbStudenInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbStudenInfo.setText("Học viên");

        lbStudentQty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbStudentQty.setText("100");

        javax.swing.GroupLayout pnStudentLayout = new javax.swing.GroupLayout(pnStudent);
        pnStudent.setLayout(pnStudentLayout);
        pnStudentLayout.setHorizontalGroup(
            pnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStudentLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbStudentIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbStudentQty)
                    .addComponent(lbStudenInfo))
                .addGap(40, 40, 40))
        );
        pnStudentLayout.setVerticalGroup(
            pnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnStudentLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbStudentQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbStudenInfo)
                    .addComponent(lbStudentIcon))
                .addGap(29, 29, 29))
        );

        add(pnStudent);

        pnMessageHint.setBackground(new java.awt.Color(0, 204, 0));

        lbMessageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_trangchu3_white_24dp.png"))); // NOI18N

        lbMessageInfo.setBackground(new java.awt.Color(255, 255, 255));
        lbMessageInfo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbMessageInfo.setText("Hộp thư");

        lbMessageQty.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbMessageQty.setText("100");

        javax.swing.GroupLayout pnMessageHintLayout = new javax.swing.GroupLayout(pnMessageHint);
        pnMessageHint.setLayout(pnMessageHintLayout);
        pnMessageHintLayout.setHorizontalGroup(
            pnMessageHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMessageHintLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbMessageIcon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnMessageHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessageQty)
                    .addComponent(lbMessageInfo))
                .addGap(40, 40, 40))
        );
        pnMessageHintLayout.setVerticalGroup(
            pnMessageHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMessageHintLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lbMessageQty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnMessageHintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbMessageInfo)
                    .addComponent(lbMessageIcon))
                .addGap(29, 29, 29))
        );

        add(pnMessageHint);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbCourseIcon;
    private javax.swing.JLabel lbCourseInfo;
    private javax.swing.JLabel lbCourseQty;
    private javax.swing.JLabel lbMessageIcon;
    private javax.swing.JLabel lbMessageInfo;
    private javax.swing.JLabel lbMessageQty;
    private javax.swing.JLabel lbStudenInfo;
    private javax.swing.JLabel lbStudentIcon;
    private javax.swing.JLabel lbStudentQty;
    private javax.swing.JPanel pnCourse;
    private javax.swing.JPanel pnMessageHint;
    private javax.swing.JPanel pnStudent;
    // End of variables declaration//GEN-END:variables
}
